application: lecturedhs
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: main.app
  login: admin

- url: /main/.*
  script: main.app
  login: required


- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest
